- .github/workflows/cleanup.yaml
- .github/workflows/examples-complete.yaml
- .github/workflows/examples-lacework.yaml
Since it takes up to 30min, it can fail and we don't know when we would check the cluster status it's not worth tu run all examples one very renovate PR. One idea could be to only run a specific test before deciding to merge the renovates PR
Additionally I add the `tf_workspace: ${{ github.ref_name }}` to the cleanup workflow to set the workspace=name of the selected branch. This will fail until https://github.com/tx-pts-dai/github-workflows/pull/50 is merged and relased
This PR will solve https://github.com/tx-pts-dai/terraform-aws-kubernetes-platform/issues/34
> dont-run-example-deployments-on-renovates-pr

- .github/workflows/examples-complete.yaml
- .github/workflows/examples-lacework.yaml
So that we dont deploy examples when there is a shared workflow version update
> fix: remove example workflow triggers

- examples/datadog/main.tf
- modules/datadog/README.md
- modules/datadog/main.tf
- modules/datadog/variables.tf
- modules/datadog/versions.tf
- replacing kubernetes secret creation by external secret
- adding new variable for DataDog secret name
The expected WF:
- The DD secret is already available in Secrets manager, created through https://github.com/tx-pts-dai/datadog-settings/blob/main/account-specific/terraform/keys.tf
- The secret name is passed to the module (default is the name we already use in the previous step).
- The external secret is created through the external secret operator and secret store.
> Fum 3224 dd k8s secrets

- modules/datadog/main.tf
I've aligned the DD sandbox secrets keys in order to have the same across all environments.
> fix: aligning secret's keys

- modules/network/ssm.tf
> fix: only create network ssm objects if vpc is created

- README.md
- moved.tf
Add moved block for eks control plane security group
Typo was fixed in previous release
None
> fix: add moved resource to prevent recreation of security groups

- .github/workflows/feature.yaml
- README.md
- files/helm/prometheus/common.yaml
Add priority class to node exporters
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml#L437
In small deployments, daemonsets need to have priority otherwise they might not get scheduled and block the platform deployment
None
> fix: add pod priority to node exporter

- README.md
- examples/lacework/main.tf
- modules/lacework/README.md
- modules/lacework/versions.tf
- modules/network/README.md
Lacework dont know how to manage tf modules and have forced an upgrade
> chore: bump lacework provider

- README.md
- karpenter.tf
a cluster with no workloads can sometimes have 4 nodes only to run the core services.
> fix: 2GB nodes are too small

- .pre-commit-config.yaml
- README.md
- files/helm/fluent-operator/common.yaml
Because of alert.
Operator uses 30MiB with max=37 on last 2 days
Adapt request on what is needed
We got alert that:
[[prod-discovery,production-discovery] Average RAM usage of fluent-operator is significantly higher than its request](https://tx-pts-dai.pagerduty.com/incidents/Q0OJBVGD4OE9YU?utm_campaign=channel&utm_source=slack)
- None
-
> Adjust fluent-op request

- karpenter.tf
v1beta is removed from 1.1.0
caused breaking change
> fix: downgrade karpenter version for backwards support (v1beta apis)

- karpenter.tf
Karpenter crash looping due to healthcheck timeout
I can see cpu and memory usage hitting the limits
This is doubling the costs of karpenter in fargate to $37+tax for two replicas.
> fix: karpenter requires more resources

- .github/workflows/feature.yaml
If we are touching anything tha can potentially change something in the module, a pr should not be able to go through without a full deployment. 
Renovate PRs will not run except if the workflow is retriggered by someone
In the future a deploy button would be helpful
> ci: run feature branch test module except for when triggered by renovate

- examples/datadog/main.tf
Default port changed in v1 helm chart
Metrics not shipped to datadog
NA
> fix: karpenter metrics port

- examples/complete/main.tf
- modules/cloudflare/README.md
- modules/cloudflare/examples/main.tf
- modules/cloudflare/examples/variables.tf
- modules/cloudflare/main.tf
- modules/cloudflare/versions.tf
Upgrade cloudflare provider to V5 and release version 1 of KaaS.
Staying up to date with cloudflare provider, remove dependencies to V4.
Yes, this is a new **MAJOR**. Resources and/or attributes in the new provider version were renamed or changed. Clients upgrading to this version should carefully think about possible downtimes. Old CF record resources will be destroyed and new ones will be created.
> feat!: upgrade cloudflare to V5 and add testing

- examples/complete/main.tf
- modules/cloudflare/README.md
- modules/cloudflare/examples/main.tf
- modules/cloudflare/main.tf
- modules/cloudflare/versions.tf
> Moving to v5 is not straightforward and there’s a blocking point. We are blocked and It’s not worth to invest time now, since we do not get any benefit out of the upgrade. There’s no optimal solutions, therefore we try to be pragmatic.
> The less painful approach is to recreate v1 pinning v4 of the cloudflare provider. So far we do not use v1 in any place for cloudflare module and since v1 has been released last Thursday we can expect no one using it.
> We do not like this approach because we believe it’s against the public module approach and the lesson learned is: releasing major version update just when we can provide a robust and validated procedure for upgrading to the new version. 
>
> feat!: KaaS major

- modules/argocd/main.tf
coalesce function returned null if argocd hub or spoke was not enabled causing a general error.
> fix: argocd value error

- CHANGELOG.md
- README.md
- docs/examples/snippets/karpenter.md
- karpenter.tf
- mkdocs.yaml
- monitoring.tf
- tests/main/main.tf
Deploy karpenter custom resources with a helmchart
How to overwrite / add node pool / class
```
karpenter = {
karpenter_resources = {
values = [
<<-EOT
nodePools:
custom:
enabled: true
labels:
environment: test
team: basic
annotations:
environment: test
team: basic
taints:
- key: "custom"
value: "true"
effect: "NoSchedule"
nodeClassRef:
name: default
group: karpenter.k8s.aws
kind: EC2NodeClass
expireAfter: "666h"
disruption:
consolidationPolicy: "WhenEmptyOrUnderutilized"
consolidateAfter: "5m"
limits:
cpu: 100
memory: 400Gi
weight: 100
requirements:
- key: "karpenter.k8s.aws/instance-category"
operator: In
values: ["c", "m"]
- key: "karpenter.k8s.aws/instance-cpu"
operator: In
values: ["8", "16", "32"]
- key: "karpenter.k8s.aws/instance-hypervisor"
operator: In
values: ["nitro"]
- key: …
```
> feat!: karpenter resources helm chart

- .github/workflows/release.yaml
Terraform registry doesnt support non semver tags
depends on https://github.com/DND-IT/github-workflows/pull/5
> ci: dont push alias releases

- modules/argocd/README.md
- modules/argocd/examples/main.tf
- modules/argocd/main.tf
- modules/argocd/variables.tf
Allow more than one hub to have access to a cluster
This allows having the dev / sandbox controllers also access clusters for testing
> fix: add support for multiple hub roles in a spoke

- addons.tf
- tests/main/main.tf
Fix issue where nested values cannot be concated causing upstream settings to be overwritten 
flexibility in settings helm inputs
none
> fix: remove addon merge configs and allow direct var input concatenation. 

- examples/datadog/main.tf
- karpenter.tf
- modules/datadog/README.md
- modules/datadog/main.tf
- modules/datadog/migrations.tf
- modules/datadog/variables.tf
enable extra operator features
align the config logic to match the rest of the platform module
Align the datadog module to use the same methods for updating values as the rest of the module. 
Removed some variables but they were not used externally.
> feat: upgrade datadog helm chart

- karpenter.tf
bug: if multiple node pools defined, the doc separator was put on the previous line making that doc ignored
> fix: update karpenter resource chart

- README.md
- examples/datadog/main.tf
- modules/network/README.md
Updating the Datadog example to show how to enable Datadog agen as external metrics server
This configuration allows the possibility to use netrics collected by the agent in HPA
none
- I validated that the external metrics servers is enabled in DAI sandbox, by looking at the DD cluster agent deployment:
```
- name: DD_EXTERNAL_METRICS_PROVIDER_USE_DATADOGMETRIC_CRD                                                                                                                                                                                 
value: "true"
```
> feat: Adding example for enabling datadog external metrics

- karpenter.tf
the chart schemas was incorrect
> fix: patch karpeneter resources chart

- modules/argocd/README.md
- modules/argocd/main.tf
- modules/argocd/variables.tf
- modules/argocd/versions.tf
Upgrading the helm provider to v3 caused the helm resources to reapply which was an old verison since we self manage argocd.
> feat: remove helm chart from argocd module
