tx-pts-dai/terraform-aws-kubernetes-platform

- .github/workflows/cleanup.yaml
- .github/workflows/examples.yaml
- addons.tf
- examples/complete/main.tf
- main.tf
depends on: https://github.com/tx-pts-dai/github-workflows/pull/35 ✅ 
Increase wait timers so full end to end deployments go through without failure. 
Tested locally the destroy
> Increase wait timers

- README.md
> doc: Add Sam in maintainers list

- README.md
- addons.tf
- main.tf
> fix: irsa role for vpc cni and enable ip prefix delgation

- README.md
- main.tf
One less variable to pass from the caller
> feat: get sso admin role into the platform itself using data aws_iam_roles

- .github/workflows/cleanup.yaml
- .github/workflows/examples-complete.yaml
- .github/workflows/examples-lacework.yaml
- .github/workflows/release.yaml
- README.md
- addons.tf
- examples/complete/main.tf
- examples/lacework/main.tf
- modules/network/README.md
- renovate.json
- variables.tf
- versions.tf
fix: update example pr workflows so that they trigger on closure
> feat: support downscaler addon

- .github/workflows/examples-complete.yaml
- .github/workflows/examples-lacework.yaml
> fix: example cleanup jobs

- examples/lacework/main.tf
- modules/lacework/README.md
- modules/lacework/main.tf
- modules/lacework/variables.tf
This will enable seeing the cluster the portal
> fix: enable agent tags and cluster agent collector

- .github/workflows/terraform-docs.yaml
- .pre-commit-config.yaml
- README.md
- modules/network/README.md
- renovate.json
> feat: group terraform minor / patch prs together

- .github/workflows/examples-cleanup.yaml
- .github/workflows/examples-complete.yaml
- .github/workflows/examples-datadog.yaml
- .github/workflows/examples-lacework.yaml
- .github/workflows/examples-simple.yaml
- README.md
- examples/complete/main.tf
- examples/datadog/main.tf
- examples/lacework/main.tf
- examples/simple/main.tf
- main.tf
- versions.tf
by using a epoch timestamp we'll keep the order of clusters in the parameter store.
> feat: use timestamp for id generation

- renovate.json
```
{
"$schema": "https://docs.renovatebot.com/renovate-schema.json",
"extends": [
"config:recommended",
":dependencyDashboard",
"github>tx-pts-dai/renovate-config:automerge-github-actions",
"github>tx-pts-dai/renovate-config:group-github-actions-minor-patch",
"github>tx-pts-dai/renovate-config:group-terraform-minor-patch"
],
"branchPrefix": "renovate_",
"timezone": "Europe/Zurich",
"dependencyDashboardTitle": "Renovate Dashboard",
"suppressNotifications": ["prIgnoreNotification"],
"commitBodyTable": true,
"rebaseWhen": "conflicted",
"platformCommit": true,
"reviewersFromCodeOwners": true,
"prCreation": "immediate",
"enabledManagers": ["dockerfile", "terraform", "github-actions", "circleci"]
}
```
> feat: Use shared renovate config

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- README.md
- modules/addon/README.md
- modules/cloudflare/README.md
- modules/datadog/README.md
- modules/lacework/README.md
- modules/network/README.md
- modules/security-group/README.md
- modules/ssm/README.md
> dbe precommit

- addons.tf
Add eks pod identity agent
https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html
Simpler method for pod authentication
None
> feat: add eks pod identity addon

- README.md
- addons.tf
- karpenter.tf
Upgrade karpenter to v1
Upgraded ALB controller and testing renovate inline datasource config
Move to stable apis
> feat: update karpenter to v1

- main.tf
> feat: Release k8s version 1.30

- .github/workflows/release.yaml
- main.tf
Fix k9s v1.30 release (trimming spaces)
> feat: fix v1.30

- .github/workflows/pre-commit.yml
Auto update tf docs and tf lint versions
How its handled https://github.com/tx-pts-dai/renovate-config/blob/main/custom-managers.json5#L19-L25
NA
> deps: add renovate tags to update versions

- .github/workflows/examples-cleanup.yaml
- .github/workflows/feature.yaml
- examples/datadog/main.tf
- karpenter.tf
- modules/datadog/main.tf
- modules/datadog/variables.tf
> chore: cleanup

- README.md
> fix: update deps

- addons.tf
> fix: add argocd hub arn list

- .github/workflows/feature.yaml
- modules/argocd/README.md
- modules/argocd/main.tf
- modules/argocd/migrations.tf
- tests/main/main.tf
> mirgate argocd to helm_release

- .github/workflows/examples-datadog.yaml
- .github/workflows/examples-lacework.yaml
- .github/workflows/examples-network.yaml
- .github/workflows/feature.yaml
- README.md
- addons.tf
- modules/datadog/README.md
- modules/datadog/main.tf
- modules/datadog/migrations.tf
> fix: remove duplicate secret
